use("bd_py");
db.Carros.find({Marca: "Porsche"});
db.Carros.find({Marca: "Ferrari"});
db.Carros.find({Modelo: "Huracán Tecnica"});
db.Carros.find({Año: 2024});
db.Carros.find({Marca: "Chevrolet Corvette"});
db.Carros.find({Año: 2023});
db.Carros.find({Modelo: "Mustang Dark Horse"});
db.Carros.find({Marca: "BMW"});
db.Carros.find({Año: 2025});
db.Carros.find({Marca: "Toyota"});
db.Celulares.find({Marca: "Apple"});
db.Celulares.find({Modelo: "Galaxy S25 Ultra"});
db.Celulares.find({Marca: "Google"});
db.Celulares.find({Marca: "Xiaomi"});
db.Celulares.find({Modelo: "Find X8 Pro"});
db.Celulares.find({Marca: "Huawei"});
db.Celulares.find({Marca: "Motorola"});
db.Celulares.find({Marca: "OnePlus"});
db.Celulares.find({Modelo: "Galaxy Z Fold 7"});
db.Celulares.find({Año: 2025});
db.Laptops.find({Modelo: "MacBook Pro M4 (16-inch)"});
db.Laptops.find({Marca: "ASUS"});
db.Laptops.find({Marca: "Dell"});
db.Laptops.find({Marca: "HP"});
db.Laptops.find({Modelo: "ThinkPad X1 Carbon Gen 13"});
db.Laptops.find({Marca: "Microsoft"});
db.Laptops.find({Año: 2024});
db.Laptops.find({Marca: "Samsung"});
db.Laptops.find({Año: 2025});
db.Laptops.find({Marca: "Acer"});
db.Motos.find({Marca: "Honda"});
db.Motos.find({Modelo: "Panigale V4 SP2"});
db.Motos.find({Marca: "Kawasaki"});
db.Motos.find({Marca: "Yamaha"});
db.Motos.find({Modelo: "M 1000 RR"});
db.Motos.find({Marca: "Aprilia"});
db.Motos.find({Año: "2024"});
db.Motos.find({Modelo: "Ninja 650"});
db.Motos.find({Marca: "KTM"});
db.Motos.find({Año: "2025"});
db.Software.find({Marca: "Microsoft"});
db.Software.find({Tipo: "CRM (Gestión de Clientes)"});
db.Software.find({Tipo: "Inteligencia Artificial (LLM)"});
db.Software.find({Modelo: "Trello"});
db.Software.find({Tipo: "Lenguaje de Programación"});
db.Software.find({Marca: "Adobe"});
db.Software.find({Tipo: "ERP (Planificación de Recursos)"});
db.Software.find({Modelo: "Google Workspace (incl. Gemini)"});
db.Software.find({Marca: "Zoom Video Comm."});
db.Software.find({Tipo: "Editor de Código"});
